import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import { defineConfig, globalIgnores } from 'eslint/config'

// PocketBase's JS VM injects these; there is no shipped globals set for
// it, and pb_data/types.d.ts only helps the editor. Listed explicitly
// rather than ignoring pb/ wholesale, so those files still get linted -
// and deliberately only the ones actually in use, since a blanket list
// would swallow the typos this is here to catch.
const pocketbaseGlobals = {
  $app: 'readonly',
  $apis: 'readonly',
  $dbx: 'readonly',
  $template: 'readonly',
  arrayOf: 'readonly',
  migrate: 'readonly',
  routerAdd: 'readonly',
  onRecordCreateRequest: 'readonly',
  onRecordUpdateRequest: 'readonly',
  unmarshal: 'readonly',
  Collection: 'readonly',
  Field: 'readonly',
  Record: 'readonly',
  BadRequestError: 'readonly',
  ForbiddenError: 'readonly',
  InternalServerError: 'readonly',
  UnauthorizedError: 'readonly',
  __hooks: 'readonly',
}

export default defineConfig([
  globalIgnores([
    'dist',
    // Generated by scripts/build-catalogue-seed.mjs - reformatting or
    // "fixing" it only survives until the next regeneration.
    'pb/pb_migrations/*_seed_procedure_catalogue.js',
  ]),
  {
    files: ['**/*.{js,jsx}'],
    extends: [
      js.configs.recommended,
      // The flat configs live under `.flat`; the top-level ones with the
      // same names are still eslintrc-shaped and ESLint 10 rejects them.
      reactHooks.configs.flat['recommended-latest'],
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    rules: {
      'no-unused-vars': ['error', { varsIgnorePattern: '^[A-Z_]' }],
    },
  },
  // Build and tooling files run in Node, not the browser.
  {
    files: ['*.config.js', 'scripts/**/*.{js,mjs}', 'mcp/**/*.js'],
    languageOptions: {
      globals: globals.node,
    },
  },
  // Hooks and migrations run in PocketBase's JS VM: CommonJS modules
  // (which is where `require` and `module` come from), no browser, and
  // none of the React rules apply. `sourceType` sits on languageOptions
  // in flat config - under parserOptions it is silently ignored.
  {
    files: ['pb/**/*.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { ...globals.es2021, ...pocketbaseGlobals },
    },
  },
])
