/// <reference path="../pb_data/types.d.ts" />

// Seeds the v2026.2 procedure code catalogue.
//
// Generated by scripts/procedure-codes.js from specs/procedure_codes/v2026.2.
// Do not edit by hand: change the spec files and publish a new version instead.
//
// Each entry carries the values this release writes ("next") and the values the
// record held in the previous release ("prev", null when this release adds it),
// so the migration can be rolled back exactly.
//
// A concept's facets are relations, so they travel as facetValueIds and are
// resolved to records here. Its synonyms are child rows, replaced as a set:
// the catalogue always states a concept's whole synonym list.
//
// Alongside the in-place upsert into the current-state tables, every change is
// appended to catalogueRevisions as an open revision (effectiveTo = ""), and
// the revision it supersedes is closed at this release's effectiveFrom - the
// RF2-shaped history in coding system spec section 6. The current-state row's
// own effectiveTo is stamped when the row goes inactive.

const CATALOGUE_RELEASE = "v2026.2";
const RELEASE_EFFECTIVE_FROM = "2026-09-18";

// catalogueRevisions.entity for the collections seeded through applyChanges.
const REVISION_ENTITY = {
  procedureFacetValues: "facetValue",
  spinalLevels: "spinalLevel",
};

const FACET_VALUE_CHANGES = [];

const LEVEL_CHANGES = [];

const CONCEPT_CHANGES = [
  {
    "key": "NSX-00129",
    "prev": null,
    "next": {
      "conceptId": "NSX-00129",
      "fields": {
        "conceptId": "NSX-00129",
        "fsn": "Percutaneous pedicle screw fixation of thoracic spine (procedure)",
        "preferredTerm": "Percutaneous thoracic pedicle screw fixation",
        "subspecialty": "spine-degenerative",
        "lateralityApplicable": false,
        "revisionApplicable": true,
        "levelApplicable": true,
        "levelKind": "vertebra",
        "levelRegions": [
          "thoracic"
        ],
        "active": true,
        "inactivationReason": "",
        "replacedBy": "",
        "effectiveFrom": "2026-09-18 00:00:00.000Z",
        "catalogueRelease": "v2026.2"
      },
      "facets": {
        "method": "MTH-0011",
        "procedureSite": "SIT-0035",
        "surgicalApproach": "APP-0014",
        "device": "DEV-0023",
        "morphology": "",
        "defaultIntent": "INT-0002"
      },
      "synonyms": [
        {
          "term": "percutaneous pedicle screws thoracic",
          "language": "en",
          "isAbbreviation": false,
          "active": true
        },
        {
          "term": "perc screws dorsal",
          "language": "en",
          "isAbbreviation": false,
          "active": true
        },
        {
          "term": "dorsal percutaneous fixation",
          "language": "en",
          "isAbbreviation": false,
          "active": true
        },
        {
          "term": "MIS fixation thoracic",
          "language": "en",
          "isAbbreviation": false,
          "active": true
        },
        {
          "term": "PPSF thoracic",
          "language": "en",
          "isAbbreviation": true,
          "active": true
        }
      ]
    }
  },
  {
    "key": "NSX-00130",
    "prev": null,
    "next": {
      "conceptId": "NSX-00130",
      "fields": {
        "conceptId": "NSX-00130",
        "fsn": "Percutaneous pedicle screw fixation of thoracolumbar spine (procedure)",
        "preferredTerm": "Percutaneous thoracolumbar pedicle screw fixation",
        "subspecialty": "spine-degenerative",
        "lateralityApplicable": false,
        "revisionApplicable": true,
        "levelApplicable": true,
        "levelKind": "vertebra",
        "levelRegions": [
          "thoracic",
          "lumbar"
        ],
        "active": true,
        "inactivationReason": "",
        "replacedBy": "",
        "effectiveFrom": "2026-09-18 00:00:00.000Z",
        "catalogueRelease": "v2026.2"
      },
      "facets": {
        "method": "MTH-0011",
        "procedureSite": "SIT-0036",
        "surgicalApproach": "APP-0014",
        "device": "DEV-0023",
        "morphology": "",
        "defaultIntent": "INT-0002"
      },
      "synonyms": [
        {
          "term": "percutaneous pedicle screws thoracolumbar",
          "language": "en",
          "isAbbreviation": false,
          "active": true
        },
        {
          "term": "perc screws dorsolumbar",
          "language": "en",
          "isAbbreviation": false,
          "active": true
        },
        {
          "term": "dorsolumbar percutaneous fixation",
          "language": "en",
          "isAbbreviation": false,
          "active": true
        },
        {
          "term": "MIS fixation thoracolumbar",
          "language": "en",
          "isAbbreviation": false,
          "active": true
        },
        {
          "term": "PPSF thoracolumbar",
          "language": "en",
          "isAbbreviation": true,
          "active": true
        }
      ]
    }
  },
  {
    "key": "NSX-00131",
    "prev": null,
    "next": {
      "conceptId": "NSX-00131",
      "fields": {
        "conceptId": "NSX-00131",
        "fsn": "Percutaneous pedicle screw fixation of lumbar spine (procedure)",
        "preferredTerm": "Percutaneous lumbar pedicle screw fixation",
        "subspecialty": "spine-degenerative",
        "lateralityApplicable": false,
        "revisionApplicable": true,
        "levelApplicable": true,
        "levelKind": "vertebra",
        "levelRegions": [
          "lumbar",
          "sacral"
        ],
        "active": true,
        "inactivationReason": "",
        "replacedBy": "",
        "effectiveFrom": "2026-09-18 00:00:00.000Z",
        "catalogueRelease": "v2026.2"
      },
      "facets": {
        "method": "MTH-0011",
        "procedureSite": "SIT-0020",
        "surgicalApproach": "APP-0014",
        "device": "DEV-0023",
        "morphology": "",
        "defaultIntent": "INT-0002"
      },
      "synonyms": [
        {
          "term": "percutaneous pedicle screws lumbar",
          "language": "en",
          "isAbbreviation": false,
          "active": true
        },
        {
          "term": "perc screws lumbar",
          "language": "en",
          "isAbbreviation": false,
          "active": true
        },
        {
          "term": "percutaneous lumbar fixation",
          "language": "en",
          "isAbbreviation": false,
          "active": true
        },
        {
          "term": "MIS fixation lumbar",
          "language": "en",
          "isAbbreviation": false,
          "active": true
        },
        {
          "term": "PPSF lumbar",
          "language": "en",
          "isAbbreviation": true,
          "active": true
        }
      ]
    }
  }
];

/**
 * Appends one open revision for a record and closes the one it supersedes.
 * prevActive is null when this release introduces the record.
 */
function recordRevision(app, entity, businessId, snapshot, isActive, prevActive) {
  const revisions = app.findCollectionByNameOrId("catalogueRevisions");

  // Close the currently-open revision (the newest one, if its effectiveTo is
  // still empty). Checked in JS rather than filtered on an empty date column.
  let prior = [];
  try {
    prior = app.findRecordsByFilter(
      "catalogueRevisions",
      "entity = {:entity} && businessId = {:businessId}",
      "-effectiveFrom",
      1,
      0,
      { entity: entity, businessId: businessId },
    );
  } catch (err) {
    prior = [];
  }
  for (const row of prior) {
    if (!row.getString("effectiveTo")) {
      row.set("effectiveTo", RELEASE_EFFECTIVE_FROM);
      app.save(row);
    }
  }

  let changeType = "update";
  if (prevActive === null || prevActive === undefined) {
    changeType = "add";
  } else if (prevActive && !isActive) {
    changeType = "retire";
  } else if (!prevActive && isActive) {
    changeType = "reactivate";
  }

  const row = new Record(revisions);
  row.set("entity", entity);
  row.set("businessId", businessId);
  row.set("release", CATALOGUE_RELEASE);
  row.set("effectiveFrom", RELEASE_EFFECTIVE_FROM);
  row.set("effectiveTo", "");
  row.set("active", isActive);
  row.set("changeType", changeType);
  row.set("snapshot", snapshot);
  app.save(row);
}

/** Rolls back recordRevision: drop this release's row, re-open the prior one. */
function unrecordRevision(app, entity, businessId) {
  let mine = [];
  try {
    mine = app.findRecordsByFilter(
      "catalogueRevisions",
      "entity = {:entity} && businessId = {:businessId} && release = {:release}",
      "",
      0,
      0,
      { entity: entity, businessId: businessId, release: CATALOGUE_RELEASE },
    );
  } catch (err) {
    mine = [];
  }
  for (const row of mine) {
    app.delete(row);
  }

  let prior = [];
  try {
    prior = app.findRecordsByFilter(
      "catalogueRevisions",
      "entity = {:entity} && businessId = {:businessId}",
      "-effectiveFrom",
      1,
      0,
      { entity: entity, businessId: businessId },
    );
  } catch (err) {
    prior = [];
  }
  for (const row of prior) {
    row.set("effectiveTo", "");
    app.save(row);
  }
}

function applyChanges(app, collectionName, keyField, changes, direction) {
  const collection = app.findCollectionByNameOrId(collectionName);
  const entity = REVISION_ENTITY[collectionName];

  for (const change of changes) {
    const values = direction === "up" ? change.next : change.prev;

    let record = null;
    try {
      record = app.findFirstRecordByData(collectionName, keyField, change.key);
    } catch (err) {
      record = null;
    }

    if (values === null) {
      // This release introduced the record, so rolling back removes it.
      if (record !== null) {
        app.delete(record);
      }
      unrecordRevision(app, entity, change.key);
      continue;
    }

    if (record === null) {
      record = new Record(collection);
    }
    for (const field in values) {
      record.set(field, values[field]);
    }
    record.set(
      "effectiveTo",
      values.active === true ? "" : RELEASE_EFFECTIVE_FROM,
    );
    app.save(record);

    if (direction === "up") {
      recordRevision(
        app,
        entity,
        change.key,
        values,
        values.active === true,
        change.prev === null ? null : change.prev.active === true,
      );
    } else {
      unrecordRevision(app, entity, change.key);
    }
  }
}

/** The facet value record a facetValueId names. */
function facetRecordId(app, facetValueId) {
  if (!facetValueId) {
    return "";
  }
  try {
    return app.findFirstRecordByData(
      "procedureFacetValues",
      "facetValueId",
      facetValueId,
    ).id;
  } catch (err) {
    throw new Error("Unknown facet value: " + facetValueId);
  }
}

function applyConcepts(app, changes, direction) {
  const collection = app.findCollectionByNameOrId("procedureConcepts");
  const synonymCollection = app.findCollectionByNameOrId(
    "procedureConceptSynonyms",
  );

  for (const change of changes) {
    const values = direction === "up" ? change.next : change.prev;

    let record = null;
    try {
      record = app.findFirstRecordByData(
        "procedureConcepts",
        "conceptId",
        change.key,
      );
    } catch (err) {
      record = null;
    }

    if (values === null) {
      // This release introduced the concept; its synonyms cascade with it.
      if (record !== null) {
        app.delete(record);
      }
      unrecordRevision(app, "concept", change.key);
      continue;
    }

    if (record === null) {
      record = new Record(collection);
    }
    for (const field in values.fields) {
      record.set(field, values.fields[field]);
    }
    for (const field in values.facets) {
      record.set(field, facetRecordId(app, values.facets[field]));
    }
    record.set(
      "effectiveTo",
      values.fields.active === true ? "" : RELEASE_EFFECTIVE_FROM,
    );
    app.save(record);

    const existing = app.findRecordsByFilter(
      "procedureConceptSynonyms",
      "concept = {:concept}",
      "",
      0,
      0,
      { concept: record.id },
    );
    for (const synonym of existing) {
      app.delete(synonym);
    }
    for (const synonym of values.synonyms) {
      const row = new Record(synonymCollection);
      row.set("concept", record.id);
      for (const field in synonym) {
        row.set(field, synonym[field]);
      }
      app.save(row);
    }

    if (direction === "up") {
      recordRevision(
        app,
        "concept",
        change.key,
        values,
        values.fields.active === true,
        change.prev === null ? null : change.prev.fields.active === true,
      );
    } else {
      unrecordRevision(app, "concept", change.key);
    }
  }
}

migrate(
  (app) => {
    // Facet values first: the concepts point at them.
    applyChanges(
      app,
      "procedureFacetValues",
      "facetValueId",
      FACET_VALUE_CHANGES,
      "up",
    );
    applyChanges(app, "spinalLevels", "spinalLevelId", LEVEL_CHANGES, "up");
    applyConcepts(app, CONCEPT_CHANGES, "up");
    console.log(
      "seeded procedure codes " +
        CATALOGUE_RELEASE +
        ": " +
        CONCEPT_CHANGES.length +
        " concept(s), " +
        FACET_VALUE_CHANGES.length +
        " facet value(s), " +
        LEVEL_CHANGES.length +
        " spinal level(s)",
    );
  },
  (app) => {
    // Concepts first: they are what points at the facet values.
    applyConcepts(app, CONCEPT_CHANGES, "down");
    applyChanges(app, "spinalLevels", "spinalLevelId", LEVEL_CHANGES, "down");
    applyChanges(
      app,
      "procedureFacetValues",
      "facetValueId",
      FACET_VALUE_CHANGES,
      "down",
    );
  },
);
